using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Kofoten.SimpleCli.Generator;

public record CommandModel(
    string Namespace,
    string ClassName,
    List<PropertyModel> Properties);

public record PropertyModel(
    string Name,
    string TypeName,
    bool IsRequired,
    bool IsCollection,
    bool IsOption,
    int Position,
    string? OptionName,
    char? ShortName
);

[Generator]
public class CliParsersSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandModels = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.BaseList is not null,
                transform: static (ctx, _) => GetCommandTarget(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(commandModels, static (spc, source) => GenerateParser(spc, source!));
    }

    private static CommandModel? GetCommandTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var inheritsCommand = classSymbol.AllInterfaces.Any(interfaceSymbol =>
            interfaceSymbol.ToDisplayString() == "Kofoten.SimpleCli.ICliCommand"
            ||
            interfaceSymbol.ToDisplayString() == "Kofoten.SimpleCli.IAsyncCliCommand");

        if (!inheritsCommand)
        {
            return null;
        }

        var properties = new List<PropertyModel>();

        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var argAttribute = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "CliArgumentAttribute");
            var optAttribute = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "CliOptionAttribute");

            if (argAttribute != null)
            {
                int position = (int)argAttribute.ConstructorArguments[0].Value!;
                properties.Add(new PropertyModel(
                    Name: member.Name,
                    TypeName: member.Type.ToDisplayString(),
                    IsRequired: member.IsRequired,
                    IsCollection: member.Type.ToDisplayString().StartsWith("System.Collections.Generic.IEnumerable"),
                    IsOption: false,
                    Position: position,
                    OptionName: null,
                    ShortName: null
                ));
            }
            else if (optAttribute != null)
            {
                string optName = (string)optAttribute.ConstructorArguments[0].Value!;
                var shortArg = optAttribute.NamedArguments.FirstOrDefault(na => na.Key == "Short");
                char? shortName = shortArg.Value.Value is char c && c != '\0' ? c : null;

                properties.Add(new PropertyModel(
                    Name: member.Name,
                    TypeName: member.Type.ToDisplayString(),
                    IsRequired: member.IsRequired,
                    IsCollection: member.Type.ToDisplayString().StartsWith("System.Collections.Generic.IEnumerable"),
                    IsOption: true,
                    Position: -1,
                    OptionName: optName,
                    ShortName: shortName
                ));
            }
        }

        return new CommandModel(
            Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName: classSymbol.Name,
            Properties: properties
        );
    }

    private static void GenerateParser(SourceProductionContext context, CommandModel command)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {command.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public class {command.ClassName}Parser");
        sb.AppendLine("{");
        sb.AppendLine($"    public {command.ClassName} Parse(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        List<Exception> errors = [];");
        sb.AppendLine();

        var arguments = command.Properties.Where(p => !p.IsOption).OrderBy(p => p.Position).ToList();
        var options = command.Properties.Where(p => p.IsOption).ToList();

        // --- 1. POSITIONAL ARGUMENTS ---
        foreach (var arg in arguments)
        {
            sb.AppendLine($"        {arg.TypeName} arg_{arg.Name} = default!;");
            sb.AppendLine($"        if (args.Length > {arg.Position})");
            sb.AppendLine("        {");
            if (arg.TypeName == "int")
            {
                sb.AppendLine($"            if (!int.TryParse(args[{arg.Position}], out arg_{arg.Name}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                errors.Add(new ArgumentException(\"Argument {arg.Name} is not an integer\"));");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine($"            arg_{arg.Name} = args[{arg.Position}];");
            }
            sb.AppendLine("        }");

            if (arg.IsRequired)
            {
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            errors.Add(new ArgumentException(\"Missing required argument {arg.Name}\"));");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        // --- 2. OPTION VARIABLES ---
        foreach (var opt in options)
        {
            if (opt.IsCollection)
            {
                var innerType = opt.TypeName.Replace("System.Collections.Generic.IEnumerable<", "").TrimEnd('>');
                sb.AppendLine($"        List<{innerType}> opt_{opt.Name} = [];");
            }
            else if (opt.TypeName == "bool")
            {
                sb.AppendLine($"        bool opt_{opt.Name} = false;");
            }
            else
            {
                sb.AppendLine($"        {opt.TypeName} opt_{opt.Name} = default!;");
            }
        }

        sb.AppendLine();

        // --- 3. STATE MACHINE LOOP ---
        sb.AppendLine("        int state = 0;");
        sb.AppendLine($"        for (int i = {arguments.Count}; i < args.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (args[i])");
        sb.AppendLine("            {");

        // Phase A: Flag Matching
        for (int i = 0; i < options.Count; i++)
        {
            var opt = options[i];
            int stateId = i + 1;

            if (!string.IsNullOrEmpty(opt.OptionName)) sb.AppendLine($"                case \"--{opt.OptionName}\":");
            if (opt.ShortName.HasValue) sb.AppendLine($"                case \"-{opt.ShortName}\":");

            sb.AppendLine($"                    state = {stateId};");
            if (opt.TypeName == "bool")
            {
                sb.AppendLine($"                    opt_{opt.Name} = true;");
            }
            sb.AppendLine("                    continue;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Phase B: Value Parsing
        sb.AppendLine("            switch (state)");
        sb.AppendLine("            {");

        for (int i = 0; i < options.Count; i++)
        {
            var opt = options[i];
            int stateId = i + 1;

            sb.AppendLine($"                case {stateId}:");
            sb.AppendLine("                    {"); // Explicit scoping for local 'v' variables

            if (opt.IsCollection)
            {
                var innerType = opt.TypeName.Replace("System.Collections.Generic.IEnumerable<", "").TrimEnd('>');
                if (innerType == "int")
                {
                    sb.AppendLine($"                        if (int.TryParse(args[i], out int v))");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            opt_{opt.Name}.Add(v);");
                    sb.AppendLine("                        }");
                    sb.AppendLine("                        else");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            errors.Add(new ArgumentException($\"Invalid {innerType} value ({{args[i]}}) for option '--{opt.OptionName}' at position {{i}}.\"));");
                    sb.AppendLine("                        }");
                }
                else
                {
                    sb.AppendLine($"                        opt_{opt.Name}.Add(args[i]);");
                }
                sb.AppendLine("                    }");
                sb.AppendLine("                    break;"); // Remains greedy, no state reset!
            }
            else if (opt.TypeName == "bool")
            {
                sb.AppendLine($"                        if (bool.TryParse(args[i], out bool v))");
                sb.AppendLine("                        {");
                sb.AppendLine($"                            opt_{opt.Name} = v;");
                sb.AppendLine("                        }");
                sb.AppendLine("                        else");
                sb.AppendLine("                        {");
                sb.AppendLine($"                            errors.Add(new ArgumentException($\"Invalid boolean value ({{args[i]}}) for option '--{opt.OptionName}' at position {{i}}.\"));");
                sb.AppendLine("                        }");
                sb.AppendLine("                    }");
                sb.AppendLine("                    state = 0;"); // Reset state
                sb.AppendLine("                    break;");
            }
            else // Single value string/int options
            {
                if (opt.TypeName == "int")
                {
                    sb.AppendLine($"                        if (int.TryParse(args[i], out int v))");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            opt_{opt.Name} = v;");
                    sb.AppendLine("                        }");
                    sb.AppendLine("                        else");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            errors.Add(new ArgumentException($\"Invalid integer value ({{args[i]}}) for option '--{opt.OptionName}' at position {{i}}.\"));");
                    sb.AppendLine("                        }");
                }
                else
                {
                    sb.AppendLine($"                        opt_{opt.Name} = args[i];");
                }
                sb.AppendLine("                    }");
                sb.AppendLine("                    state = 0;"); // Reset state
                sb.AppendLine("                    break;");
            }
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // --- 4. RETURN BLOCK ---
        sb.AppendLine("        if (errors.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {command.ClassName}()");
        sb.AppendLine("            {");
        foreach (var prop in command.Properties)
        {
            string prefix = prop.IsOption ? "opt_" : "arg_";
            sb.AppendLine($"                {prop.Name} = {prefix}{prop.Name},");
        }
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        throw new AggregateException(errors);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{command.ClassName}Parser.g.cs", sb.ToString());
    }
}