using System.Collections.Generic;
using System.ComponentModel;

namespace Kofoten.NativeCli.Internal;

/// <summary>
/// This class contains helper methods for use in the code generated by the Kofoten.NativeCli library.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public static class GeneratorHelperSources
{
    public static Dictionary<TKey, TValue> CreateDictionaryWithOverwrite<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>> pairs)
    {
        var result = new Dictionary<TKey, TValue>();
        foreach (var pair in pairs)
        {
            result[pair.Key] = pair.Value;
        }

        return result;
    }
}
