name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: simple-cli-arc-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet run --verbosity normal --project ./Kofoten.SimpleCli.Test/Kofoten.SimpleCli.Test.csproj
